name: Check
on:
  pull_request:
    types:
      - opened
  push:
    branches:
    - main
    - prod

jobs:
  legacy-daweb-api-middleware-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Build Docker image
      working-directory: .
      run: docker build -t repeater -f ./Dockerfile .

  legacy-daweb-api-middleware:
    runs-on: ubuntu-latest

    steps:
    - name: Check code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Conventional Commits
      uses: webiny/action-conventional-commits@v1.1.0

    - name: Install dependencies
      run: npm ci

    - name: Typecheck
      run: npm run typescript-check
    
    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test

    - name: Check for non generated files
      working-directory: .
      run: git diff --exit-code
